### ISSUE TITLE
How do I solve run errors using Docker Compose

### ISSUE THREAD

**Issue by guowan123** [IDEA-Research/deepdataspace#105]
#0 396.9 Progress: resolved 2025, reused 0, downloaded 1862, added 1895
#0 397.9 Progress: resolved 2025, reused 0, downloaded 1912, added 1945
#0 398.9 Progress: resolved 2025, reused 0, downloaded 1944, added 1976
#0 399.9 Progress: resolved 2025, reused 0, downloaded 1946, added 1977
#0 400.9 Progress: resolved 2025, reused 0, downloaded 1990, added 2024
#0 401.9 Progress: resolved 2025, reused 0, downloaded 1990, added 2025, done
#0 401.9 .../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#0 401.9 .../core-js@3.28.0/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#0 401.9 .../es5-ext@0.10.62/node_modules/es5-ext postinstall$  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
#0 401.9 .../node_modules/@sentry/cli install$ node ./scripts/install.js
#0 402.0 .../node_modules/core-js-pure postinstall: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#0 402.0 .../node_modules/core-js-pure postinstall: The project needs your help! Please consider supporting core-js:
#0 402.0 .../node_modules/core-js-pure postinstall: > https://opencollective.com/core-js 
#0 402.0 .../node_modules/core-js-pure postinstall: > https://patreon.com/zloirock 
#0 402.0 .../node_modules/core-js-pure postinstall: > https://boosty.to/zloirock 
#0 402.0 .../node_modules/core-js-pure postinstall: > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 
#0 402.0 .../node_modules/core-js-pure postinstall: I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md 
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: The project needs your help! Please consider supporting of core-js:
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: > https://opencollective.com/core-js 
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: > https://patreon.com/zloirock 
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md 
#0 402.0 .../node_modules/core-js-pure postinstall: Done
#0 402.0 .../core-js@3.28.0/node_modules/core-js postinstall: Done
#0 402.1 .../es5-ext@0.10.62/node_modules/es5-ext postinstall: Done
#0 402.2 .../node_modules/@sentry/cli install: [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.75.2/sentry-cli-Linux-x86_64
#0 1371.5 .../node_modules/@sentry/cli install: Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.75.2/sentry-cli-Linux-x86_64.
#0 1371.5 .../node_modules/@sentry/cli install: Error code: ETIMEDOUT
#0 1371.5 .../node_modules/@sentry/cli install: Failed
#0 1371.5 ?ELIFECYCLE? Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c npm install -g pnpm@8.4.0 &&     pnpm install --frozen-lockfile &&     pnpm run build:app" did not complete successfully: exit code: 1

**Comment by xifanii** [comment]
@guowan123 
This seems to be a network timeout error when loading the Sentry dependency package. You can try rebuilding the Docker container. 
If the error persists and you are in China, you can try replacing the 'registry=https://registry.npmmirror.com' line in the '.npmrc' file with 'registry=https://registry.cnpm.org', and then rebuild the Docker container.

**Comment by raotaohub** [comment]
```
ENTRYCLI_CDNURL=https://cdn.npm.taobao.org/dist/sentry-cli
sentrycli_cdnurl=https://cdn.npm.taobao.org/dist/sentry-cli
```

 add config above in .npmrc file
