### ISSUE TITLE
How to disable an keypoint invisible in pose annotation?

### ISSUE THREAD

**Issue by ledinhtri97** [IDEA-Research/deepdataspace#106]
Hello as the topic.
I could not find how to disable the keypoint invisible in when do pose annotation?
please help! thank you

**Comment by ledinhtri97** [comment]
I also want to save the keypoints to continue next frame but when recheck the previous frame it did not save the keypoint but only the bounding

**Comment by ledinhtri97** [comment]
![image](https://github.com/IDEA-Research/deepdataspace/assets/16860306/922db636-1bc9-49f0-93e6-aaa67234bed8)
the bounding box saving is zero?

**Comment by cefeng06** [comment]
Thank you for your feedback and suggestions! Regarding the keypoints issues (visibility of editing points, exporting with bbox fields), we're actively working on a new release to address these concerns. Stay tuned for the upcoming version!

**Comment by cefeng06** [comment]
Hi! We've just released the latest version of deepdataspace (v0.9.1), addressing the mentioned issue. To update, simply run the following command locally:
`pip install --upgrade deepdataspace`
