### ISSUE TITLE
I could not load the keypoint labeled in edit of the collaborate tool

### ISSUE THREAD

**Issue by ledinhtri97** [IDEA-Research/deepdataspace#110]
Hello, I already update the newest version 0.9.1
when I use the collaborate labeling function. With the keypoints labeling tool, everything is fine when labeling and saving success notify. I want to look back the editor keypoint labeling and view the list images labeled. 

only the bounding box available but not the key-point saving. I also want to check extract ground truth with script bellow.

```
dataset = DataSet.find_one({"id": dataset_id})
    # create the image model dynamically
    ImageModel = Image(dataset_id)
    num_images = ImageModel.count_num({})
    print(f"Exporting dataset of {num_images} images: {dataset.name}")
    output_images = []
    # find all images in the dataset sorted by idx and id, and exporting them
    images = ImageModel.find_many({}, sort=[("idx", 1), ("id", 1)])
    for idx, image in enumerate(images):
        # export all fields of the image
        output = {
            "id": image.id,
            "idx": image.idx,
            "url": image.url_full_res,
            "thumbnail": image.url,
            "width": image.width,
            "height": image.height,
            "metadata": json.loads(image.metadata),
            "objects": []
        }
        for anno_obj in image.objects:
            # print(anno_obj)
            obj_data = anno_obj.to_dict(exclude=["compare_result", "matched_det_idx", "confirm_type"]) # exclude some fields
            print(obj_data["points"])
            if len(obj_data["points"]):
                output["objects"].append(obj_data)
        output_images.append(output)
        if len(output["objects"]):
            print("---", output)
        # print(f"{idx + 1}/{num_images}: exported image {image.id} of {len(output['objects'])} objects")


    output = {
        "dataset_id": dataset_id,
        "dataset_name": dataset.name,
        "images": output_images
    }

    os.makedirs(output_dir, exist_ok=True)
    with open(f"{output_dir}/{dataset.name}_{dataset_id}.json", "w", encoding="utf8") as fp:
        json.dump(output, fp, ensure_ascii=False)
```

but there is no object had labeled too.

**Comment by cefeng06** [comment]
When reviewing exported annotation data in the dataset module, please take note of the "Display options" in the upper right corner. Make sure you have selected "keypoints" to visualize both bounding boxes and keypoints.
<img width="330" alt="截屏2023-12-11 22 31 05" src="https://github.com/IDEA-Research/deepdataspace/assets/72333144/78a3d3e4-3c28-43d3-a924-778193930d5d">

**Comment by ledinhtri97** [comment]
@cefeng06 
I dont saw that options
![image](https://github.com/IDEA-Research/deepdataspace/assets/16860306/6d8b2bb8-c275-4ccc-87ee-2ece58edddc9)

But the main issue I think also from it lost annotation when save data, the keypoints become to be the box instead in Edit mode
![image](https://github.com/IDEA-Research/deepdataspace/assets/16860306/7dcfddd9-9602-4b55-a4e2-dfd801a47b8e)

**Comment by cefeng06** [comment]
Sorry, the Collaborative Mode of annotation tool currently only supports saving bbox type. We plan to expand to other types in future releases. We recommend trying the Quick Mode in the meantime. Thank you for your feedback !

**Comment by ledinhtri97** [comment]
@cefeng06 thank you for your response. I got that
