### ISSUE TITLE
Consuming the API via CLI

### ISSUE THREAD

**Issue by israel-cj** [IDEA-Research/deepdataspace#125]
Great work!
I wonder if there is a way of consuming the API via CLI without touching the frontend? 
Let's say I have 100 images and I want to do the same procedure with those and not one by one. 
Thanks in advance

**Comment by imhuwq** [comment]
Hello @israel-cj, we're currently developing a cloud API platform that allows users to leverage our algorithms through Python code. It's still a work in progress, and at the moment, our [documentation](https://algos.deepdataspace.com/#/) is available only in Chinese. If you're interested, please feel free to send us an email at weiliu@idea.edu.cn, and we'll do our best to accommodate your needs.

**Comment by israel-cj** [comment]
Dear @imhuwq thank you very much for the help, I will contact Weiliu.
